/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MAIN;

import BD.Conection;
import java.sql.SQLException;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author GON
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    
    public Conection mysqldata = new Conection();
    DefaultListModel To = new DefaultListModel();
    DefaultListModel Doing = new DefaultListModel();
    DefaultListModel Done = new DefaultListModel();
    String DefaultItem = "Select..........................";
    public App() {
        initComponents();
        this.setLocationRelativeTo(null);
        cbxProject.addItem(DefaultItem);
        cbxProjectFull();
        ListTo.setModel(To);
        ListDoing.setModel(Doing);
        ListDone.setModel(Done);
        
    }
    
    public void cbxProjectFull(){
        try{
            mysqldata.getProyect();
          do{
                cbxProject.addItem(mysqldata.data.getString("name_project"));
            }
          while(mysqldata.data.next());
        }catch(Exception e){}
    }
    
    public void ListToDoingDone(){
        To.removeAllElements();
        Doing.removeAllElements();
        Done.removeAllElements();
        try{
            mysqldata.getTask(cbxProject.getItemAt(cbxProject.getSelectedIndex()));
          do{
              if(mysqldata.data.getInt("id_stage")== 1){
                  To.addElement(mysqldata.data.getString("name_task"));
              }else if (mysqldata.data.getInt("id_stage")== 2){
                  Doing.addElement(mysqldata.data.getString("name_task"));
              }else if(mysqldata.data.getInt("id_stage")== 3){
                  Done.addElement(mysqldata.data.getString("name_task"));
                  
              }
                
            }
          while(mysqldata.data.next());
        }catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProfile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        cbxProject = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListTo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListDoing = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListDone = new javax.swing.JList<>();
        btnDetailsTo = new javax.swing.JButton();
        btnDetailsDoing = new javax.swing.JButton();
        btnDetailsDone = new javax.swing.JButton();
        btnNewTask = new javax.swing.JButton();
        btnToDoing = new javax.swing.JButton();
        btnToTo = new javax.swing.JButton();
        btnDoingDone = new javax.swing.JButton();
        btnDoneDoing = new javax.swing.JButton();
        btnFinishTask = new javax.swing.JButton();
        btnEditProject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        jLabel2.setText("Proyects:");

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        cbxProject.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbxProjectPopupMenuWillBecomeVisible(evt);
            }
        });
        cbxProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProjectActionPerformed(evt);
            }
        });

        jLabel3.setText("To");

        jLabel4.setText("Doing");

        jLabel5.setText("Done");

        ListTo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListToMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListTo);

        ListDoing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListDoingMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListDoing);

        ListDone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListDoneMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ListDone);

        btnDetailsTo.setText("Details");
        btnDetailsTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsToActionPerformed(evt);
            }
        });

        btnDetailsDoing.setText("Details");
        btnDetailsDoing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsDoingActionPerformed(evt);
            }
        });

        btnDetailsDone.setText("Details");
        btnDetailsDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsDoneActionPerformed(evt);
            }
        });

        btnNewTask.setText("New Task");
        btnNewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTaskActionPerformed(evt);
            }
        });

        btnToDoing.setText(">");
        btnToDoing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToDoingActionPerformed(evt);
            }
        });

        btnToTo.setText("<");
        btnToTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToToActionPerformed(evt);
            }
        });

        btnDoingDone.setText(">");
        btnDoingDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoingDoneActionPerformed(evt);
            }
        });

        btnDoneDoing.setText("<");
        btnDoneDoing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneDoingActionPerformed(evt);
            }
        });

        btnFinishTask.setText("Finish Proyect");
        btnFinishTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishTaskActionPerformed(evt);
            }
        });

        btnEditProject.setText("Edit");
        btnEditProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnProfile)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDetailsTo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnToDoing, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnToTo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDetailsDoing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDoingDone))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDoneDoing, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDetailsDone, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFinishTask, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(114, 114, 114))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxProject, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditProject)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfile)
                    .addComponent(jLabel2)
                    .addComponent(btnNew)
                    .addComponent(cbxProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditProject))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetailsTo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDoingDone)
                            .addComponent(btnDetailsDoing)
                            .addComponent(btnToTo)
                            .addComponent(btnToDoing)
                            .addComponent(btnNewTask)
                            .addComponent(btnDetailsDone)
                            .addComponent(btnDoneDoing)
                            .addComponent(btnFinishTask))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProjectActionPerformed
        
        ListToDoingDone();
    }//GEN-LAST:event_cbxProjectActionPerformed

    private void ListToMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListToMouseClicked
         
         ListDoing.clearSelection();
         ListDone.clearSelection();
    }//GEN-LAST:event_ListToMouseClicked

    private void ListDoingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListDoingMouseClicked
         ListTo.clearSelection();
         ListDone.clearSelection();
    }//GEN-LAST:event_ListDoingMouseClicked

    private void ListDoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListDoneMouseClicked
         ListDoing.clearSelection();
         ListTo.clearSelection();
    }//GEN-LAST:event_ListDoneMouseClicked

    private void btnNewTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTaskActionPerformed
        if(cbxProject.getItemAt(cbxProject.getSelectedIndex())!=DefaultItem){
            
            AddNewTask newTaskView = new AddNewTask(this,true);
            newTaskView.selectProject = cbxProject.getItemAt(cbxProject.getSelectedIndex());
            newTaskView.stageList = 1;
            newTaskView.txtProjectData.setText(cbxProject.getItemAt(cbxProject.getSelectedIndex()));
            cbxProject.setSelectedIndex(0);
            newTaskView.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona un proyecto para agregar tareas","¡Ups!",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnNewTaskActionPerformed

    private void btnToDoingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToDoingActionPerformed
        try{
        mysqldata.UpdateTask(2, (String) To.getElementAt(ListTo.getSelectedIndex()));
        mysqldata.UpdateStartDate((String) To.getElementAt(ListTo.getSelectedIndex()));
         ListToDoingDone();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Selecciona una Tarea para agregar a Doing","¡Ups!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnToDoingActionPerformed

    private void btnToToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToToActionPerformed
       try{
        mysqldata.UpdateTask(1, (String) Doing.getElementAt(ListDoing.getSelectedIndex()));
        mysqldata.UpdateStartDateNull((String) Doing.getElementAt(ListDoing.getSelectedIndex()));
         ListToDoingDone();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Selecciona una Tarea para agregar a to","¡Ups!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnToToActionPerformed

    private void btnDoingDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoingDoneActionPerformed
        try{
        mysqldata.UpdateTask(3, (String) Doing.getElementAt(ListDoing.getSelectedIndex()));
        mysqldata.UpdateEndDate((String) Doing.getElementAt(ListDoing.getSelectedIndex()));
         ListToDoingDone();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Selecciona una Tarea para agregar a Done","¡Ups!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDoingDoneActionPerformed

    private void btnDoneDoingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneDoingActionPerformed
        try{
        mysqldata.UpdateTask(2, (String) Done.getElementAt(ListDone.getSelectedIndex()));
        mysqldata.UpdateEndDateNull((String) Done.getElementAt(ListDone.getSelectedIndex()));
         ListToDoingDone();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Selecciona una Tarea para agregar a Doing","¡Ups!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDoneDoingActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        Profile DescProfile = new Profile(this,true);
        DescProfile.setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
       NewProject addproject = new NewProject(this,true);
       addproject.setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnFinishTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishTaskActionPerformed
       EndProject end = new EndProject(this,true);
       end.txtendPro.setText(cbxProject.getItemAt(cbxProject.getSelectedIndex()));
       cbxProject.setSelectedIndex(0);
       end.setVisible(true);
    }//GEN-LAST:event_btnFinishTaskActionPerformed

    private void btnDetailsToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsToActionPerformed
       try{
       Details opendetailsTo = new Details(this,true);
       opendetailsTo.txtProject.setText(cbxProject.getItemAt(cbxProject.getSelectedIndex()));
       opendetailsTo.taskname = (String) To.getElementAt(ListTo.getSelectedIndex());
       opendetailsTo.load();
       cbxProject.setSelectedIndex(0);
       opendetailsTo.setVisible(true);
       }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Selecciona una tarea","¡ups!",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_btnDetailsToActionPerformed

    private void btnDetailsDoingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsDoingActionPerformed
        try{
        Details opendetailsDoing = new Details(this,true);
        opendetailsDoing.txtProject.setText(cbxProject.getItemAt(cbxProject.getSelectedIndex()));
        opendetailsDoing.taskname = (String) Doing.getElementAt(ListDoing.getSelectedIndex());
        opendetailsDoing.load();
        cbxProject.setSelectedIndex(0);
        opendetailsDoing.setVisible(true);
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Selecciona una tarea","¡ups!",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_btnDetailsDoingActionPerformed

    private void btnDetailsDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsDoneActionPerformed
        try{
        Details opendetailsDone = new Details(this,true);
        opendetailsDone.txtProject.setText(cbxProject.getItemAt(cbxProject.getSelectedIndex()));
        opendetailsDone.taskname = (String) Done.getElementAt(ListDone.getSelectedIndex());
        opendetailsDone.load();
        cbxProject.setSelectedIndex(0);
        opendetailsDone.setVisible(true);
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Selecciona una tarea","¡ups!",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_btnDetailsDoneActionPerformed

    private void cbxProjectPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbxProjectPopupMenuWillBecomeVisible
        cbxProject.removeAllItems();
        cbxProject.addItem(DefaultItem);
        cbxProjectFull();
        
    }//GEN-LAST:event_cbxProjectPopupMenuWillBecomeVisible

    private void btnEditProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProjectActionPerformed
        if(!cbxProject.getItemAt(cbxProject.getSelectedIndex()).equals(DefaultItem)){
        
        EditProject editPro = new EditProject(this,true);
        editPro.name = cbxProject.getItemAt(cbxProject.getSelectedIndex());
        editPro.projectName();
        cbxProject.setSelectedIndex(0);
        editPro.setVisible(true);
        }else{
        JOptionPane.showMessageDialog(null, "Selecciona projecto para editar","¡Ups!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditProjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListDoing;
    private javax.swing.JList<String> ListDone;
    private javax.swing.JList<String> ListTo;
    private javax.swing.JButton btnDetailsDoing;
    private javax.swing.JButton btnDetailsDone;
    private javax.swing.JButton btnDetailsTo;
    private javax.swing.JButton btnDoingDone;
    private javax.swing.JButton btnDoneDoing;
    private javax.swing.JButton btnEditProject;
    private javax.swing.JButton btnFinishTask;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNewTask;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnToDoing;
    private javax.swing.JButton btnToTo;
    public javax.swing.JComboBox<String> cbxProject;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
