/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MAIN;

import java.awt.JobAttributes;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author GON
 */
public class Details extends javax.swing.JDialog {

    /**
     * Creates new form Details
     */
    App detailsTask = new App();
    public String taskname;
    public Details(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTask = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cbxPriority = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCDate = new javax.swing.JLabel();
        txtSDate = new javax.swing.JLabel();
        txtFDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProject = new javax.swing.JLabel();
        btnDefaul = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Task:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 33, 60, -1));
        getContentPane().add(txtTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 30, 410, -1));

        jLabel2.setText("Description:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 56, 70, -1));

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 56, 410, 148));

        jLabel3.setText("Priority:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 214, -1, -1));

        btnEdit.setBackground(new java.awt.Color(255, 153, 153));
        btnEdit.setText("Edit");
        btnEdit.setBorderPainted(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 63, -1));

        btnDelete.setBackground(new java.awt.Color(255, 153, 153));
        btnDelete.setText("Delete");
        btnDelete.setBorderPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        cbxPriority.setBackground(new java.awt.Color(255, 153, 153));
        cbxPriority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(cbxPriority, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel4.setText("Create Date:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jLabel5.setText("Start Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel6.setText("Finish date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        txtCDate.setText("date");
        getContentPane().add(txtCDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        txtSDate.setText("date");
        getContentPane().add(txtSDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        txtFDate.setText("date");
        getContentPane().add(txtFDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel7.setText("Project:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 10, 60, -1));

        txtProject.setText("Project");
        getContentPane().add(txtProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        btnDefaul.setBackground(new java.awt.Color(255, 153, 153));
        btnDefaul.setText("Restart");
        btnDefaul.setToolTipText("");
        btnDefaul.setBorderPainted(false);
        btnDefaul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaulActionPerformed(evt);
            }
        });
        getContentPane().add(btnDefaul, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppImages/1.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 520, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            if(!txtTask.getText().equals(taskname) || !txtDescription.getText().equals(detailsTask.mysqldata.data.getString("description")) || !cbxPriority.getItemAt(cbxPriority.getSelectedIndex()).equals(detailsTask.mysqldata.data.getString("priority"))){
                detailsTask.mysqldata.UpdateAllTask(txtTask.getText(), txtDescription.getText(), cbxPriority.getItemAt(cbxPriority.getSelectedIndex()),taskname);
                taskname = txtTask.getText();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "edit the fields","¡ups!",JOptionPane.WARNING_MESSAGE);
        }
        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDefaulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaulActionPerformed
       load();
    }//GEN-LAST:event_btnDefaulActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       load();
       detailsTask.mysqldata.DeleteTaskSelect(taskname);
       this.dispose();
    }//GEN-LAST:event_btnDeleteActionPerformed
    public void load(){
        detailsTask.mysqldata.showTask(taskname);
        try {
            txtTask.setText(taskname);
            txtDescription.setText(detailsTask.mysqldata.data.getString("description"));
            cbxPriority.setSelectedIndex(detailsTask.mysqldata.data.getInt("priority")-1);
            txtCDate.setText(detailsTask.mysqldata.data.getString("create_date"));
            txtSDate.setText(detailsTask.mysqldata.data.getString("start_date"));
            txtFDate.setText(detailsTask.mysqldata.data.getString("end_date"));
        } catch (SQLException ex) {
            Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Details dialog = new Details(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDefaul;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cbxPriority;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtCDate;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JLabel txtFDate;
    public javax.swing.JLabel txtProject;
    private javax.swing.JLabel txtSDate;
    public javax.swing.JTextField txtTask;
    // End of variables declaration//GEN-END:variables
}
